version: "2.1"
services:
  web:
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_SSL_PRIVATE: /etc/nginx/demo-key.pem
      NGINX_SSL_PUBLIC:  /etc/nginx/demo-cert.pem
      MYSQL_DB_CA:       /etc/nginx/ca-cert.pem
      MYSQL_DB_KEY:      /etc/nginx/mysql-key.pem
      MYSQL_DB_CERT:     /etc/nginx/mysql-cert.pem
      MYSQL_DB_VERIFY:   "true"
    volumes:
      - /opt/arcus-certs/ca-cert.pem:/etc/nginx/ca-cert.pem:ro
      - /opt/arcus-certs/demo-key.pem:/etc/nginx/demo-key.pem:ro
      - /opt/arcus-certs/demo-cert.pem:/etc/nginx/demo-cert.pem:ro
      - /opt/arcus-certs/mysql-key.pem:/etc/nginx/mysql-key.pem:ro
      - /opt/arcus-certs/mysql-cert.pem:/etc/nginx/mysql-cert.pem:ro
  db:
    volumes:
      - /opt/arcus-certs/ca-cert.pem:/etc/mysql/ca-cert.pem:ro
      - /opt/arcus-certs/mysql-key.pem:/etc/mysql/mysql-key.pem:ro
      - /opt/arcus-certs/mysql-cert.pem:/etc/mysql/mysql-cert.pem:ro
      - /opt/arcus-certs/require_ssl.sql:/docker-entrypoint-initdb.d/require_ssl.sql:ro
    command:
      - --ssl-ca=/etc/mysql/ca-cert.pem
      - --ssl-key=/etc/mysql/mysql-key.pem
      - --ssl-cert=/etc/mysql/mysql-cert.pem
